disabled_rules:
  - trailing_whitespace
  - empty_enum_arguments
  - block_based_kvo
  
# opt_in_rules:
#   - vertical_whitespace_between_cases

line_length:
    warning: 200
    error: 250
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true

function_body_length:
    warning: 300
    error: 500

file_length:
  ignore_comment_only_lines: true

identifier_name:
  excluded: # excluded via string array
    - id

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Carthage
  - AudioLearning/Rx.playground
  - AudioLearning/ClosureDemo.playground
  - AudioLearning/Resources/Demo
  # - AudioLearningTests